services:
  - docker:dind

variables:
  # dockerfile for building artifact image
  BUILD_DOCKERFILE: build.dockerfile
  IMAGE_NAME: registry.gitlab.com/tokend/tickets/web-admin
  IMAGE_BUILD_NAME: $IMAGE_NAME:$CI_COMMIT_SHA

stages:
- build

build:
  image: docker:latest
  stage: build
  only:
    - master
  tags:
    - tokend
  script:
    # login to docker registry
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build --build-arg RSA_KEY="$SSH_PRIVATE_KEY" --build-arg BUILD_ENV=config/default.env.js --pull -t $IMAGE_BUILD_NAME .
    - docker push $IMAGE_BUILD_NAME
